"""Isolated localhost Match workflow proof. Production definitions come from the
tracked catalog (reconfirmed unchanged 2026-10-09). Frozen historical data are read
only fixture inputs; no Calibration protocol or implementation runs here.
Requires PostgreSQL roles anon/authenticated/service_role and port 55439.
"""
import copy
import hashlib
import json
import os
import re
from pathlib import Path
import subprocess
import time
import unittest
import uuid

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
PSQL = r'C:\Program Files\PostgreSQL\17\bin\psql.exe'
ENV = dict(os.environ,PGCLIENTENCODING='UTF8',PGCONNECT_TIMEOUT='3')
PREFIX = 'membermatch_' + str(time.time_ns())
CAT = json.loads((REPO/'supabase/source-snapshots/2026-10-08/production-catalog.json').read_text(encoding='utf8'))
BASE = json.loads((REPO/'analysis/rating-calibration01-a/dataset.json').read_text(encoding='utf8'))
ADMIN='b3bb0000-0000-4000-8000-000000000001'
MEMBER='b3bb0000-0000-4000-8000-000000000002'
OTHER='b3bb0000-0000-4000-8000-000000000003'
FORCED='b3bb0000-0000-4000-8000-000000000004'
IDS=sorted(p['id'] for p in BASE['players'])[:4]


def quote(value):
    return "'"+str(value).replace("'","''")+"'"


def call(sql,db):
    return subprocess.run([PSQL,'-X','-w','-h','127.0.0.1','-p','55439','-U','postgres','-d',db,
                           '-At','-v','ON_ERROR_STOP=1'],input=sql,encoding='utf8',capture_output=True,env=ENV,timeout=45)


def run(sql,db):
    p=call(sql,db)
    assert p.returncode==0,p.stderr
    return p.stdout.strip()


def insert_rows(table,rows):
    result=[]
    for row in rows:
        columns=','.join('"'+k+'"' for k in row)
        values=','.join('r."'+k+'"' for k in row)
        data=quote(json.dumps(row))
        result.append(f'INSERT INTO public.{table}({columns}) SELECT {values} FROM json_populate_record(NULL::public.{table},{data}::json) r;')
    return '\n'.join(result)


def fixture_schema():
    sql=['CREATE SCHEMA auth;',
         "CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;",
         "CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.role',true),'') $$;",
         'GRANT USAGE ON SCHEMA auth TO anon,authenticated,service_role;']
    types={(x['table'],x['column']):x['type'] for x in BASE['column_types']}
    tables=sorted({c['table_name'] for c in CAT['columns']})
    for table in tables:
        fields=[]
        for c in CAT['columns']:
            if c['table_name']!=table:continue
            name=c['column_name'];type_=types.get((table,name),c['data_type'])
            if type_=='ARRAY':type_=c['udt_name'].lstrip('_')+'[]'
            default=' DEFAULT '+c['column_default'] if c['column_default'] else ''
            if name in ['id','replay_order'] and type_ in ['bigint','integer'] and not default:
                default=' GENERATED BY DEFAULT AS IDENTITY'
            primary=' PRIMARY KEY' if name=='id' else ''
            required=' NOT NULL' if c['is_nullable']=='NO' else ''
            fields.append('"'+name+'" '+type_+default+required+primary)
        sql.append('CREATE TABLE public.'+table+'('+','.join(fields)+');')
    sql.append('ALTER TABLE public.rating_adjustments ADD UNIQUE(request_id);')
    players=[dict(p,full_name='Synthetic '+p['id'][:8]) for p in BASE['players']]
    matches=[{k:v for k,v in m.items() if k!='played_date'}|{'status':'APPROVED'} for m in BASE['matches']]
    profiles=[dict(id=a,full_name='Match synthetic',role=role,is_active=True,membership_status='APPROVED',must_change_password=forced,player_id=player)
              for a,role,forced,player in [(ADMIN,'ADMIN',False,None),(MEMBER,'MEMBER',False,IDS[0]),(OTHER,'MEMBER',False,IDS[2]),(FORCED,'MEMBER',True,IDS[1])]]
    for table,rows in [('players',players),('profiles',profiles),('rating_settings',BASE['settings']),
                       ('rating_match_weights',BASE['weights']),('matches',matches),
                       ('match_players',BASE['lineups']),('rating_events',BASE['events'])]:
        sql.append(insert_rows(table,rows))
    definitions=';\n'.join(f['definition'] for f in [f for f in CAT['functions'] if f['name'] in ['_approve_match_internal', '_generate_match_fund_internal', '_get_active_rating_version', '_rebuild_ratings_internal', 'confirm_match_by_opponent', 'correct_rating_adjustment', 'create_my_pending_match', 'create_pending_match', 'current_user_business_access_active', 'guard_match_mutation', 'guard_match_player_mutation', 'record_rating_adjustment', 'record_rating_adjustment_active', 'reject_match_by_opponent', 'resubmit_my_rejected_match', 'set_pending_match_players', 'update_my_rejected_pending_match', 'void_match', 'current_user_player_id', 'get_my_pending_match_confirmations', 'approve_match', 'approve_match_active', 'reject_pending_match']])+';\n'
    def preserve_body(match):
        body=match.group(1).replace('\\','\\\\').replace("'","''").replace('\r','\\r').replace('\n','\\n')
        return "AS E'"+body+"'"
    sql.append(re.sub(r'AS \$function\$(.*?)\$function\$',preserve_body,definitions,flags=re.S))
    selected=set(['_approve_match_internal', '_generate_match_fund_internal', '_get_active_rating_version', '_rebuild_ratings_internal', 'confirm_match_by_opponent', 'correct_rating_adjustment', 'create_my_pending_match', 'create_pending_match', 'current_user_business_access_active', 'guard_match_mutation', 'guard_match_player_mutation', 'record_rating_adjustment', 'record_rating_adjustment_active', 'reject_match_by_opponent', 'resubmit_my_rejected_match', 'set_pending_match_players', 'update_my_rejected_pending_match', 'void_match', 'current_user_player_id', 'get_my_pending_match_confirmations', 'approve_match', 'approve_match_active', 'reject_pending_match'])
    for f in CAT['functions']:
        if f['name'] not in selected:continue
        sig='public.'+f['signature']
        sql.append('REVOKE ALL ON FUNCTION '+sig+' FROM PUBLIC,anon,authenticated,service_role;')
        for role,key in [('authenticated','authenticated_execute'),('anon','anon_execute'),('service_role','service_execute')]:
            if f[key]:sql.append('GRANT EXECUTE ON FUNCTION '+sig+' TO '+role+';')
    for t in CAT['triggers']:
        if t['table'] in ['matches','match_players']:sql.append(t['definition']+';')
    return '\n'.join(sql)



ACTORS=[MEMBER,'b3bb0000-0000-4000-8000-000000000005',OTHER,'b3bb0000-0000-4000-8000-000000000006']
UNRELATED='b3bb0000-0000-4000-8000-000000000007'
UNLINKED='b3bb0000-0000-4000-8000-000000000008'
DELEGATE='b3bb0000-0000-4000-8000-000000000009'

class MatchContract(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.template=PREFIX+'_template'
        run('CREATE DATABASE '+cls.template,'postgres')
        try:
            run(fixture_schema(),cls.template)
            run("UPDATE players SET player_type='CLUB' WHERE id="+quote(IDS[1]),cls.template)
            run(insert_rows('profiles',[
                dict(id=ACTORS[1],full_name='Creator A2',role='MEMBER',is_active=True,membership_status='APPROVED',must_change_password=False,player_id=IDS[1]),
                dict(id=ACTORS[3],full_name='Creator B2',role='MEMBER',is_active=True,membership_status='APPROVED',must_change_password=False,player_id=IDS[3]),
                dict(id=UNRELATED,full_name='Unrelated',role='MEMBER',is_active=True,membership_status='APPROVED',must_change_password=False,player_id=sorted(p['id'] for p in BASE['players'])[4]),
                dict(id=UNLINKED,full_name='Unlinked',role='MEMBER',is_active=True,membership_status='APPROVED',must_change_password=False),
                dict(id=DELEGATE,full_name='Approver',role='MEMBER',is_active=True,membership_status='APPROVED',must_change_password=False,can_approve_matches=True)
            ]),cls.template)
            run((REPO/'supabase/migrations/202610090002_member_my_matches_creator_context.sql').read_text(encoding='utf8'),cls.template)
        except BaseException:
            run('DROP DATABASE '+cls.template+' WITH(FORCE)','postgres');raise

    @classmethod
    def tearDownClass(cls):run('DROP DATABASE '+cls.template+' WITH(FORCE)','postgres')
    def setUp(self):
        self.db=PREFIX+'_'+uuid.uuid4().hex[:8]
        run('CREATE DATABASE '+self.db+' TEMPLATE '+self.template,'postgres')
    def tearDown(self):run('DROP DATABASE '+self.db+' WITH(FORCE)','postgres')
    def prefix(self,actor):
        return "SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub',"+quote(actor)+",false); SELECT set_config('request.jwt.claim.role','authenticated',false); "
    def rpc(self,name,args='',actor=MEMBER):
        p=call(self.prefix(actor)+'SELECT public.'+name+'('+args+');',self.db)
        self.assertEqual(p.returncode,0,p.stderr)
        return json.loads(p.stdout.strip().splitlines()[-1])
    def deny(self,name,args,actor,error):
        p=call(self.prefix(actor)+'SELECT public.'+name+'('+args+');',self.db)
        self.assertNotEqual(p.returncode,0,p.stdout);self.assertIn(error,p.stderr)
    def create(self,creator=MEMBER):
        args=','.join(["'2026-10-09T04:00:00Z'","'CLUB_RATED'","'POINTS'",'11','7']+[quote(i) for i in IDS]+["'Fixture'"])
        return self.rpc('create_my_pending_match',args,creator)['match_id']
    def events(self,match):return int(run("SELECT count(*) FROM rating_events WHERE match_id="+quote(match),self.db))
    def test_confirm_symmetry(self):
        for c in range(4):
            for who in range(4):
                with self.subTest(creator=c,confirmer=who):
                    match=self.create(ACTORS[c]); self.assertEqual(self.events(match),0)
                    eligibility=json.loads(run(self.prefix(ACTORS[who])+"SELECT coalesce(jsonb_agg(r),'[]') FROM public.get_my_pending_match_confirmations() r WHERE match_id="+quote(match),self.db).splitlines()[-1])
                    self.assertEqual(eligibility[0]['can_confirm'],(c//2 != who//2))
                    if c==who:self.deny('confirm_match_by_opponent',quote(match),ACTORS[who],'CREATOR_CANNOT_CONFIRM')
                    elif c//2==who//2:self.deny('confirm_match_by_opponent',quote(match),ACTORS[who],'CREATOR_TEAM_CANNOT_CONFIRM')
                    else:
                        self.rpc('confirm_match_by_opponent',quote(match),ACTORS[who]);self.assertEqual(self.events(match),4)
                        self.deny('confirm_match_by_opponent',quote(match),ACTORS[who],'MATCH_NOT_PENDING');self.assertEqual(self.events(match),4)
    def test_reject_symmetry_and_resubmit(self):
        for c in range(4):
            for who in range(4):
                with self.subTest(creator=c,rejector=who):
                    match=self.create(ACTORS[c]);args=quote(match)+",'Score correction'"
                    if c==who:self.deny('reject_match_by_opponent',args,ACTORS[who],'CREATOR_CANNOT_REJECT')
                    elif c//2==who//2:self.deny('reject_match_by_opponent',args,ACTORS[who],'CREATOR_TEAM_CANNOT_REJECT')
                    else:
                        self.rpc('reject_match_by_opponent',args,ACTORS[who]);self.assertEqual(self.events(match),0)
                        self.deny('confirm_match_by_opponent',quote(match),ACTORS[who],'MATCH_REJECTED_WAITING_CREATOR_RESUBMIT')
                        update=','.join([quote(match),"'2026-10-09T04:00:00Z'","'CLUB_RATED'","'POINTS'",'11','9']+[quote(i) for i in IDS]+["'Edited'"])
                        self.rpc('update_my_rejected_pending_match',update,ACTORS[c]);self.rpc('resubmit_my_rejected_match',quote(match),ACTORS[c])
                        self.assertEqual(run('SELECT created_by FROM matches WHERE id='+quote(match),self.db),ACTORS[c])
                        self.rpc('confirm_match_by_opponent',quote(match),ACTORS[who]);self.assertEqual(self.events(match),4)
    def test_unrelated_denied(self):
        match=self.create()
        self.deny('confirm_match_by_opponent',quote(match),UNRELATED,'CONFIRMER_NOT_IN_MATCH')
        self.deny('reject_match_by_opponent',quote(match)+",'Test reason'",UNRELATED,'REJECTOR_NOT_IN_MATCH')
    def test_create_participant_security(self):
        args=','.join(["'2026-10-09T04:00:00Z'","'CLUB_RATED'","'POINTS'",'11','7']+[quote(i) for i in IDS]+["'Fixture'"])
        p=call(self.prefix(UNRELATED)+'SELECT create_my_pending_match('+args+');',self.db)
        self.assertNotEqual(p.returncode,0);self.assertIn('MEMBER_MUST_PARTICIPATE',p.stderr)
    def test_admin_and_delegate_override(self):
        for actor in [ADMIN,DELEGATE]:
            match=self.create(ACTORS[3]);self.rpc('approve_match_active',quote(match),actor);self.assertEqual(self.events(match),4)
            match=self.create(ACTORS[1]);self.rpc('reject_pending_match',quote(match)+",'Admin intervention'",actor)
            self.assertEqual(run('SELECT status FROM matches WHERE id='+quote(match),self.db),'INVALID');self.assertEqual(self.events(match),0)
    def test_my_matches_scope_and_positions(self):
        # Existing baseline history is preserved; new 24 fixtures vary creator and status.
        for i in range(24):
            match=self.create(ACTORS[i%4])
            if i%3==0:self.rpc('approve_match_active',quote(match),ADMIN)
            elif i%3==1:self.rpc('reject_match_by_opponent',quote(match)+",'Fixture rejection'",ACTORS[(i%4+2)%4])
        for i,actor in enumerate(ACTORS):
            data=self.rpc('get_my_matches',actor=actor)
            expected=json.loads(run("SELECT coalesce(jsonb_agg(DISTINCT match_id),'[]') FROM match_players WHERE player_id="+quote(IDS[i])+" OR partner_player_id="+quote(IDS[i]),self.db))
            self.assertEqual({m['id'] for m in data['matches']},set(expected));self.assertEqual(len(data['matches']),len(expected))
            self.assertEqual(data['player_id'],IDS[i]);self.assertTrue(all('created_by' not in m for m in data['matches']))
        unlinked=self.rpc('get_my_matches',actor=UNLINKED);self.assertIsNone(unlinked['player_id']);self.assertEqual(unlinked['matches'],[])
        self.deny('get_my_matches',quote(IDS[0]),UNRELATED,'does not exist')
    def test_creator_context(self):
        for i,actor in enumerate(ACTORS):
            match=self.create(actor)
            rows=json.loads(run(self.prefix(ADMIN)+'SELECT jsonb_agg(r) FROM get_match_creator_context() r;',self.db).splitlines()[-1])
            expected=run('SELECT full_name FROM profiles WHERE id='+quote(actor),self.db)
            self.assertEqual(next(r for r in rows if r['match_id']==match)['creator_name'],expected)
        p=call('UPDATE matches SET created_by=NULL WHERE id='+quote(match),self.db)
        self.assertNotEqual(p.returncode,0)
        run('DELETE FROM profiles WHERE id='+quote(actor),self.db)
        rows=json.loads(run(self.prefix(ADMIN)+'SELECT jsonb_agg(r) FROM get_match_creator_context() r;',self.db).splitlines()[-1])
        self.assertIsNone(next(r for r in rows if r['match_id']==match)['creator_name'])
    def test_inactive_read_eligibility(self):
        self.create()
        run("UPDATE players SET status='INACTIVE' WHERE id="+quote(IDS[2]),self.db)
        self.deny('get_my_pending_match_confirmations','',OTHER,'ACTIVE_MEMBER_PLAYER_REQUIRED')
    def test_partner_only_inclusion(self):
        match=self.create()
        run("ALTER TABLE match_players DISABLE TRIGGER USER; DELETE FROM match_players WHERE match_id="+quote(match)+" AND player_id="+quote(IDS[1])+"; ALTER TABLE match_players ENABLE TRIGGER USER;",self.db)
        self.assertIn(match,{m['id'] for m in self.rpc('get_my_matches',actor=ACTORS[1])['matches']})
    def test_migration_source_drift_guard(self):
        definition=next(f['definition'] for f in CAT['functions'] if f['name']=='get_my_pending_match_confirmations')
        # Simulate production source drift before a first migration apply.
        run('DROP FUNCTION get_my_matches(); DROP FUNCTION get_match_creator_context();',self.db)
        run(definition.replace('MEMBER_CREATED_MATCH_REQUIRED','DRIFTED_MEMBER_CREATED_MATCH_REQUIRED'),self.db)
        p=call((REPO/'supabase/migrations/202610090002_member_my_matches_creator_context.sql').read_text(encoding='utf8'),self.db)
        self.assertNotEqual(p.returncode,0);self.assertIn('MATCH_CONFIRMATION_READ_MODEL_SOURCE_DRIFT',p.stderr)
        self.assertEqual(run("SELECT count(*) FROM pg_proc WHERE proname IN ('get_my_matches','get_match_creator_context')",self.db),'0')

    def test_read_model_security(self):
        self.deny('get_match_creator_context','',MEMBER,'MATCH_APPROVAL_PERMISSION_REQUIRED')
        self.deny('get_my_matches','',FORCED,'BUSINESS_ACCESS_REQUIRED')
        self.deny('get_match_creator_context','',FORCED,'BUSINESS_ACCESS_REQUIRED')
        self.assertEqual(run("SELECT has_function_privilege('anon','get_my_matches()','EXECUTE') OR has_function_privilege('anon','get_match_creator_context()','EXECUTE')",self.db),'f')
        self.assertEqual(run("SELECT count(*) FROM pg_proc WHERE proname IN ('get_my_matches','get_match_creator_context') AND prosecdef AND proconfig=ARRAY['search_path=public, pg_temp']",self.db),'2')

if __name__=='__main__':unittest.main(verbosity=2)
